### PR TITLE
Added Function to add multiple Verbs with / Example: PUT/PATCH will m…

### PR DESCRIPTION
**Pull request by Flori00**
Added Function to add multiple Verbs with / Example: PUT/PATCH will make a PUT and a PATCH which are both identical, instead of the operationId

### CODE REVIEW

**Comment by Shwetap05** [comment]
>             foreach (var operationElement in operationElements)

Why would you need two verb for the same API? 

---
Refers to: src/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration/InternalOpenApiGenerator.cs:473 in f6caa8e. [](commit_id = f6caa8ea346f6d226715fdae8e923341e5d79c35, deletion_comment = False)

**Comment by Flori00** [comment]
I need 2Verbs because in the API I am working on, there are sometimes put and patch verb in one function. But I want to document both of them.

**Comment by Shwetap05** [comment]
Sorry can you elaborate more, are you saying you have a single API which is sometimes called with PUT and sometime with PATCH, how does that work? That doesn't follow REST api guidelines. Will you be able to provide code snippet of an example mimicking your scenario will help me understand this more.

---
In reply to: [514919518](https://github.com/microsoft/OpenAPI.NET.CSharpAnnotations/pull/215#issuecomment-514919518) [](ancestors = 514919518)

**Comment by Flori00** [comment]
Not needed anymore

**Pull request closed without merging**
