### PR TITLE
When Alternate tags are provided remove Param tag for which in attribute is not specified 

### PR DESCRIPTION
**Pull request by Shwetap05**
As the title says.

### CODE REVIEW

**Comment by PerthCharern** [comment]
This means that customers can't mix and match old and new formats in certain cases. Say, they can't use pathParam and then have a param for query parameters that do not have "in" but are present in the URL (since that URL population comes later in the PopulateInAttributeFilter.cs).

It's fine to me. 

If we care about that, then we can also break down the PopulateInAttributeFilter to only add "in" without throwing error, and have a separate filter at the end of the preprocessing step to just throw errors if it still sees anything that misses "in".

**Comment by PerthCharern** [comment]
The case I'm afraid of is:

- People use the "header" tag. 
- They have the "param" tags without "in" - because they only rely on the URL matching.

---
In reply to: [391504084](https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/pull/125#issuecomment-391504084) [](ancestors = 391504084)

**Comment by PerthCharern** [comment]
It's not that big of a deal. At the end of the day, these are all best-effort fixes.

If we would like to help with case above, then we can break the PopulateInAttributeFilter into two parts: 1) Adding "in" based on URL 2) Throw error when "in" doesn't exist

Then, we can reorder the default filter set to:

PopulateInAttributeFilter#1
ConvertAlternativeParamTagsFilter
PopulateInAttributeFilter#2

---
In reply to: [391504455](https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/pull/125#issuecomment-391504455) [](ancestors = 391504455,391504084)

**Comment by Shwetap05** [comment]
This is fixed now.

---
In reply to: [391505197](https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/pull/125#issuecomment-391505197) [](ancestors = 391505197,391504455,391504084)

**Comment by PerthCharern** [comment]
Looks good to me! Thanks for making the change!

**Pull request merged**
